
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-DriverAvailability-postEndpoint","number":23,"title":"Wt driver availability post endpoint","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/23"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-DriverAvailability-RecordAndFixtures","number":22,"title":"Wt driver availability record and fixtures","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/22"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-UsersToggleButtonPrettier","number":21,"title":"Wt - added colors to toggle buttons and prettied font","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/21"}]
