
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBdHhOA","is_bot":false,"login":"dhwang154","name":""},"headRefName":"dhwang154-form","number":39,"title":" FEATURE: Create DriverAvailabilityForm (Driver Availability) #16","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/39"},{"author":{"id":"MDQ6VXNlcjQ3NTAwNDYw","is_bot":false,"login":"AllenHsm","name":"Allen Hu"},"headRefName":"ah-dev","number":37,"title":"Table component for Driver Availability plus tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/37"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-ReadableChat","number":35,"title":"fixed chat display","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/35"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-ApplyRider","number":34,"title":"FEATURE: All users should not be able to see \"Apply to be a Rider\" if they are a rider","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/34"},{"author":{"id":"U_kgDOB3EM8A","is_bot":false,"login":"notaryaman","name":""},"headRefName":"as-getendpoints","number":33,"title":" GET for Driver Availability Controller (Driver Availability) ","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/33"},{"author":{"id":"U_kgDOB3EM8A","is_bot":false,"login":"notaryaman","name":""},"headRefName":"as-putendpoints","number":31,"title":" PUT for Driver Availability Controller (Driver Availability) ","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-4/pull/31"}]
